### ISSUE TITLE
Regarding the personal letters

### ISSUE THREAD

**Issue by SaraTomillo** [Arquisoft/citizensLoader_i2a#7]
>  The system will generate personal letters that will be sent to each user by email. This task will be done by the Council and is not part of this system.

This appears in the explanation of our system and then as optional part it says:

> [Optional] The system could be extended to emit the letters using other formats like Microsoft Word or PDF

So does this mean the letter generation is our task or just provinding a way to get the data to write them?

**Comment by ClaudiaCF** [comment]
as we don't have any answers i suppose we can do it so once we have all the users created, we will generate a word document for each of the users informing of their users and passwords
